// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $('a[href*=#]:not([href=#])').click(function() {
      var ref, target;
      if (location.pathname.replace(/^\//, '') === this.pathname.replace(/^\//, '') && location.hostname === this.hostname) {
        target = $(this.hash);
        target = (ref = target.length) != null ? ref : {
          target: $("[name=" + (this.hash.slice(1)) + "]")
        };
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 1000);
          return false;
        }
      }
    });
    return $(window).bind('scroll', function() {
      if ($(window).scrollTop() > 500) {
        return $('body header nav').addClass('fixed');
      } else {
        return $('body header nav').removeClass('fixed');
      }
    });
  });

}).call(this);
